---
title: "Texas Adults With Diabetes or Obesity by Educational Attainment and Income, 2021"
author: "Kaitlan Wong"
format: html
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(readxl)
library(dplyr)
```

```{r}
# Read the Excel file
data <- read_excel("C:/Users/kaitl/Documents/Every Texan/R/ADA/Education and Income/Obesity Diabetes Rates BRFSS 2011-21.xlsx")

# create education dataframe
education <- data %>%
  filter(`Demographic Category` == "Education")

# create income dataframe
income <- data %>%
  filter(`Demographic Category` == "Income Level")
```

```{r}
# Create line graph showing disease by educational attainment over time

# Convert disease rate variable to numeric
education$`Percent Yes` <- as.numeric(education$`Percent Yes`)


# Create line graph

ggplot(education, aes(x = Year, y = `Percent Yes`,
                 color = `Demographic Group`, linetype = Disease)) +
  geom_line(size = 1) +
  scale_color_manual(values = c("Less Than High School" = "#009E73", "High School Graduate" = "#56B4E9", "Some College" = "#E69F00", "College Graduate" = "#CC79A7"),
                     breaks = c("Less Than High School", "High School Graduate", "Some College", "College Graduate")
    ) +
  scale_linetype_manual(values = c("Obesity" = "solid", "Diabetes" = "dotted")) +
  labs(
    x = "Year", 
    y = "Percent With Disease", 
    color = "Educational Attainment", 
    linetype = "Disease",
    title = "Percentage of Texas Adults With Diabetes or Obesity by\n Educational Attainment, 2011-2021",
    caption = "Source: Every Texan analysis of Texas Department of State Health Services BRFSS data."
      ) +
   scale_y_continuous(labels = scales::percent,
                     limits = c(0, 0.5)) +  # Adjust the y-axis limits as needed
  scale_x_continuous(breaks = data$Year) +  # Set breaks to include every year
  theme_minimal() +
  theme(legend.spacing.y = unit(.25, "cm"),
        legend.text = element_text(margin = margin(r = 1)),
        axis.title.y = element_text(margin = margin(r = 15)),
        axis.text.y = element_text(margin = margin(r = 10)),
        axis.text.x = element_text(angle = 45, hjust = 1),  # Angle and alignment of x-axis labels
        plot.caption = element_text(hjust = 0, margin = margin(t = 10, l = 0))  # Left-align the caption with top and left margins)
        )


# Save the graph as an image
ggsave("Disease Rates by edu 2011-2021.png", width = 10, height = 6, units = "in")

```

```{r}
# Create line graph showing disease by income level over time

# Convert disease rate variable to numeric
income$`Percent Yes` <- as.numeric(income$`Percent Yes`)


# Create line graph

ggplot(income, aes(x = Year, y = `Percent Yes`,
                 color = `Demographic Group`, linetype = Disease)) +
  geom_line(size = 1) +
  scale_color_manual(values = c("Less Than $25,000" = "#009E73", "$25,000-$49,999" = "#56B4E9", "$50,000 or More" = "#E69F00"),
                     breaks = c("Less Than $25,000", "$25,000-$49,999", "$50,000 or More")
    ) +
  scale_linetype_manual(values = c("Obesity" = "solid", "Diabetes" = "dotted")) +
  labs(
    x = "Year", 
    y = "Percent With Disease", 
    color = "Income Level", 
    linetype = "Disease",
    title = "Percentage of Texas Adults With Diabetes or Obesity by\n Income Level, 2011-2021",
    caption = "Source: Every Texan analysis of Texas Department of State Health Services BRFSS data."
      ) +
   scale_y_continuous(labels = scales::percent,
                     limits = c(0, 0.5)) +  # Adjust the y-axis limits as needed
  scale_x_continuous(breaks = data$Year) +  # Set breaks to include every year
  theme_minimal() +
  theme(legend.spacing.y = unit(.25, "cm"),
        legend.text = element_text(margin = margin(r = 1)),
        axis.title.y = element_text(margin = margin(r = 15)),
        axis.text.y = element_text(margin = margin(r = 10)),
        axis.text.x = element_text(angle = 45, hjust = 1),  # Angle and alignment of x-axis labels
        plot.caption = element_text(hjust = 0, margin = margin(t = 10, l = 0))  # Left-align the caption with top and left margins)
        )


# Save the graph as an image
ggsave("Disease Rates by income 2011-2021.png", width = 10, height = 6, units = "in")
```

```{r}
# Create side by side double charts for 2021

# Filter the 'education' and 'income' data for the year 2021
education_2021 <- education %>%
  filter(Year == 2021)

income_2021 <- income %>%
  filter(Year == 2021)

# Define the desired order for x-axis labels
education_order <- c("Less Than High School", "High School Graduate", "Some College", "College Graduate")
income_order <- c("Less Than $25,000", "$25,000-$49,999", "$50,000 or More")

# Convert 'Demographic Group' to a factor with the desired order
education_2021$`Demographic Group` <- factor(education_2021$`Demographic Group`, levels = education_order)
income_2021$`Demographic Group` <- factor(income_2021$`Demographic Group`, levels = income_order)

# Combine the education and income data into one dataframe
combined_data <- rbind(
  mutate(education_2021, Category = "Educational Attainment"),
  mutate(income_2021, Category = "Income Level")
)

# Create custom labels with line breaks
combined_data$`Demographic Group` <- factor(combined_data$`Demographic Group`,
  labels = c("Less Than\nHigh School", "High School\nGraduate", "Some\nCollege", "College\nGraduate", "Less Than\n$25,000", "$25,000-\n$49,999", "$50,000\nor More")
)

# Create the combined bar chart with facets
combined_chart <- ggplot(combined_data, aes(x = `Demographic Group`, y = `Percent Yes`, fill = Disease)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.7) +
 geom_text(aes(label = paste0(round(`Percent Yes` * 100), "%")), position = position_dodge(width = 0.7), vjust = -0.5, size = 3) +  # Round and add "%" symbol to the labels
  labs(
    x = NULL,  # Remove x-axis title
    y = "Percent With Disease",
    fill = "Disease",
    title = "Percentage of Texas Adults With Diabetes or Obesity by Educational\nAttainment and Income Level in 2021",
    caption = "Source: Every Texan analysis of Texas Department of State Health Services BRFSS data."
  ) +
  theme_minimal() +
  theme(
    legend.position = "top",  # Place the legend at the top
    axis.text.x = element_text(angle = 0, hjust = 0.5, size = 8),  # Centered x-axis labels and smaller font size
    legend.text = element_text(size = 8),  # Smaller legend font size
    legend.title = element_text(size = 9)  # Smaller legend title font size
  ) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 0.5)) +  # Adjust the y-axis limits as needed +
  facet_wrap(~ Category, ncol = 2, scales = "free_x")

# Increase the plot width and height
ggsave("Combined Double Bar Chart 2021.png", combined_chart, width = 12, height = 8, units = "in")



# Print the combined chart to display it
print(combined_chart)


```
